In [1]:
import numpy as np

In [2]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [37]:
print (x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [38]:
print (y) 

[[0]
 [1]
 [1]
 [0]]


In [39]:
#Step 2 build model

num_epochs = 100000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [40]:
print (syn0)

[[ 0.17648766 -0.00646875  0.70437746 -0.06022623]
 [-0.40858504 -0.01815998  0.0358011  -0.89501063]
 [-0.89052856  0.39362025  0.05883443 -0.00580337]]


In [41]:
print (syn1)

[[ 0.19864727]
 [-0.08712055]
 [ 0.90713318]
 [ 0.58740663]]


In [42]:
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [43]:
#Step 3 Train Model

for j in range(num_epochs):
    #feed forward through layers 0,1, and 2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    #how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print ('Epoch:' + str(j) + ". Error:" + str(np.mean(np.abs(l2_error))))
    
    #in what direction is the target value?
    l2_delta = l2_error*nonlin(l2, deriv=True)
    
    #how much did each l1 value contribute to l2 error
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta= l1_error * nonlin(l1,deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Epoch:0. Error:0.500349679832
Epoch:10000. Error:0.0103838084773
Epoch:20000. Error:0.00710397504638
Epoch:30000. Error:0.00571968345688
Epoch:40000. Error:0.00491194143313
Epoch:50000. Error:0.00436776633547
Epoch:60000. Error:0.00396963508778
Epoch:70000. Error:0.00366226423847
Epoch:80000. Error:0.00341579906964
Epoch:90000. Error:0.00321252430564
